before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - replacements:
      linux: Linux
      amd64: x86_64
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/vilsol/beacon:{{ .Major }}"
      - "ghcr.io/vilsol/beacon:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/vilsol/beacon:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/vilsol/beacon:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
