{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "beacon.fullname" . }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "beacon.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "beacon.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}